### ISSUE TITLE
gifify on google compute cloud

### ISSUE THREAD

**Issue by jcsk** [max-mapper/gifify-docker#2]
I installed docker locally (OSX) with glifify-docker and it works great!

But when I tried to install it on a container-optimized Google Compute Engine image, I get an empty file:

~$ sudo docker run -it --rm -v /home/test:/data maxogden/gifify pod.mp4 -o pod.gif
gifsicle:<stdin>: empty file

Here is the version:
test@gifify:~$ sudo docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

The images:
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
maxogden/gifify     latest              9cd65cf635b4        3 months ago        476.5 MB
google/cadvisor     0.8.0               4cde3eeb4b8d        4 months ago        17.79 MB
kubernetes/pause    go                  6c4579af347b        10 months ago       239.8 kB

And the directory:
$ ls -l
total 584
-rw-r--r-- 1 root test 594916 May 19 21:15 pod.mp4
-rw-r--r-- 1 root root         0 May 19 22:24 pod.gif

**Comment by max-mapper** [comment]
hmmmmmm maybe its using an old version of docker that doesnt support the `-v` volume mounting functionality?

**Comment by jcsk** [comment]
Looks like it was just a botched mp4. I tried another and it worked flawlessly!

Thanks!
